#!/usr/bin/env bash
set -e

QUERY='
  query($endCursor: String) {
    viewer {
      repositories(first: 100, after: $endCursor) {
        nodes { nameWithOwner }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
'

repos=$(gh api graphql --paginate -f query="${QUERY}" --jq '.data.viewer.repositories.nodes.[].nameWithOwner')
selected_repo=$(echo "$repos" | fzf --height 40% --layout=reverse --border)

echo $selected_repo
